server:
  port: 8002
spring:
  application:
    name: loveshopping-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loveshopping_product?characterEncoding=utf8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/yangchao/loveshopping/mapper/*Mapper.xml
  type-aliases-package: cn.yangchao.loveshopping.domain,cn.yangchao.loveshopping.query
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
