server:
  port: 4396
spring:
  application:
    name: loveshopping-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-4396.com
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: loveshopping-plat #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从4396端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀