server:
  port: 8002
spring:
  application:
    name: loveshopping-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loveshopping_product
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/yangchao/loveshopping/mapper/*Mapper.xml
  type-aliases-package: cn.yangchao.loveshopping.domain,cn.yangchao.loveshopping.query
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka   #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
